### PR TITLE
FOGL-2506 Changes in footer

### PR DESCRIPTION
**Pull request by MonikaSharma06**
Changes in footer:
1) If content is small, show footer at the bottom of the screen
2) If page content is longer than viewport, show footer after scrolling to the bottom

### CODE REVIEW

**Review by praveen-garg — CHANGES_REQUESTED** [review]
I don't see much improvements with new commits.

Not sure why `.container.is-fluid {
    min-height:` chnages are in?

**Review by praveen-garg — DISMISSED** [review]
When content height is longer than viewport, then footer's gap to the bottom is very low compared to other. (e.g. in Syslog and Audit logs pages)

**Review by shariq1501 — DISMISSED** [review]

**Review by praveen-garg — DISMISSED** [review]
lgtm! only 1 minor padding fix for growing content.

**Review by praveen-garg — APPROVED** [review]
lgtm!

**Review by shariq1501 — APPROVED** [review]

**Pull request merged**
